import type {
  Device,
  Configuration,
  Audit,
  Finding,
  Framework,
  DriftEvent,
  AiMapping,
  Report,
  DashboardData,
} from "./types";

export const user = {
  id: "USR-001",
  name: "Ayush Sharma",
  email: "admin@nexus-comply.local",
  role: "Security Administrator",
  organization: "Nexus Security Operations",
  avatar: "AS",
};

export const devices: Device[] = [
  {
    id: "dev-001",
    hostname: "core-rtr-01",
    vendor: "Cisco",
    platform: "IOS-XE",
    ip: "10.24.8.1",
    model: "Catalyst 8300",
    osVersion: "17.9.4a",
    environment: "Production",
    location: "Mumbai / DC-1",
    status: "At risk",
    lastAudit: "Sep 23, 2026",
    risk: 68,
    compliance: 74,
    criticality: "Critical",
    findings: 5,
  },
  {
    id: "dev-002",
    hostname: "edge-fw-01",
    vendor: "Fortinet",
    platform: "FortiOS",
    ip: "10.24.8.254",
    model: "FortiGate 200F",
    osVersion: "7.2.5",
    environment: "Production",
    location: "Mumbai / DC-1",
    status: "Healthy",
    lastAudit: "Sep 22, 2026",
    risk: 42,
    compliance: 88,
    criticality: "High",
    findings: 2,
  },
  {
    id: "dev-003",
    hostname: "dist-sw-01",
    vendor: "Cisco",
    platform: "NX-OS",
    ip: "10.24.16.10",
    model: "Nexus 9300",
    osVersion: "10.3.3",
    environment: "Production",
    location: "Bengaluru / DC-2",
    status: "At risk",
    lastAudit: "Sep 20, 2026",
    risk: 51,
    compliance: 81,
    criticality: "High",
    findings: 3,
  },
  {
    id: "dev-004",
    hostname: "branch-fw-01",
    vendor: "Palo Alto",
    platform: "PAN-OS",
    ip: "10.32.1.1",
    model: "PA-440",
    osVersion: "11.1.2",
    environment: "Staging",
    location: "Delhi / Branch",
    status: "Healthy",
    lastAudit: "Sep 18, 2026",
    risk: 35,
    compliance: 91,
    criticality: "Medium",
    findings: 1,
  },
];

export const configurations: Configuration[] = [
  {
    id: "CFG-001",
    deviceId: "dev-001",
    version: 14,
    filename: "core-rtr-01-v14.cfg",
    uploadedBy: "Ayush Sharma",
    uploadedAt: "Sep 23, 2026 09:40",
    size: "48 KB",
    status: "Normalized",
    hash: "sha256:7f9b8c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b",
    lines: [
      "! Cisco IOS-XE Configuration File - core-rtr-01",
      "version 17.9",
      "service timestamps debug datetime msec",
      "service timestamps log datetime msec",
      "service password-encryption",
      "hostname core-rtr-01",
      "!",
      "aaa new-model",
      "aaa authentication login default local",
      "aaa authorization exec default local",
      "!",
      "transport input telnet ssh",
      "!",
      "ip domain-name nexus.internal",
      "ip ssh version 2",
      "ip ssh time-out 60",
      "ip ssh authentication-retries 3",
      "!",
      "interface GigabitEthernet0/0/0",
      " description Uplink to Core Provider",
      " ip address 10.24.8.1 255.255.255.0",
      " no ip proxy-arp",
      " no ip redirects",
      "!",
      "line con 0",
      " exec-timeout 10 0",
      " stopbits 1",
      "line vty 0 4",
      " exec-timeout 10 0",
      " transport input telnet ssh",
      " login authentication default",
      "!",
      "end",
    ],
  },
  {
    id: "CFG-002",
    deviceId: "dev-001",
    version: 13,
    filename: "core-rtr-01-v13.cfg",
    uploadedBy: "Ayush Sharma",
    uploadedAt: "Sep 16, 2026 14:15",
    size: "47 KB",
    status: "Active",
    hash: "sha256:4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b",
    lines: [
      "! Cisco IOS-XE Configuration File - core-rtr-01 v13",
      "version 17.9",
      "hostname core-rtr-01",
      "service password-encryption",
      "aaa new-model",
      "transport input ssh",
      "end",
    ],
  },
  {
    id: "CFG-003",
    deviceId: "dev-002",
    version: 8,
    filename: "edge-fw-01-v8.conf",
    uploadedBy: "Aarav Mehta",
    uploadedAt: "Sep 22, 2026 11:20",
    size: "62 KB",
    status: "Normalized",
    hash: "sha256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    lines: [
      "# FortiOS Configuration - edge-fw-01",
      "config system global",
      "    set hostname edge-fw-01",
      "    set admin-ssh-port 22",
      "    set admin-telnet disable",
      "end",
    ],
  },
  {
    id: "CFG-004",
    deviceId: "dev-003",
    version: 5,
    filename: "dist-sw-01-v5.cfg",
    uploadedBy: "Ayush Sharma",
    uploadedAt: "Sep 20, 2026 16:30",
    size: "39 KB",
    status: "Normalized",
    hash: "sha256:8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c",
    lines: [
      "! Cisco NX-OS Configuration - dist-sw-01",
      "hostname dist-sw-01",
      "feature ssh",
      "ssh key rsa 2048",
      "no feature telnet",
      "end",
    ],
  },
  {
    id: "CFG-005",
    deviceId: "dev-004",
    version: 3,
    filename: "branch-fw-01-v3.xml",
    uploadedBy: "Security Automation",
    uploadedAt: "Sep 18, 2026 08:00",
    size: "54 KB",
    status: "Normalized",
    hash: "sha256:5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d",
    lines: [
      "<!-- PAN-OS XML Configuration - branch-fw-01 -->",
      '<config version="11.1.0">',
      '  <mgt-config><users><entry name="admin"/></users></mgt-config>',
      "</config>",
    ],
  },
];

export const driftEvents: DriftEvent[] = [
  {
    id: "drift-001",
    deviceId: "dev-001",
    version: 14,
    date: "Sep 23, 2026",
    change: "Enabled Telnet on management access (insecure legacy protocol)",
    impact: "Increased",
    controls: ["CIS-5.1", "IA-2", "AC-17"],
    riskBefore: 58,
    riskAfter: 68,
    finding: "FND-00418",
  },
  {
    id: "drift-002",
    deviceId: "dev-001",
    version: 13,
    date: "Sep 16, 2026",
    change: "Updated administrative access policy and AAA authentication",
    impact: "Decreased",
    controls: ["CIS-5.1", "AC-17"],
    riskBefore: 64,
    riskAfter: 58,
    finding: "FND-00419",
  },
  {
    id: "drift-003",
    deviceId: "dev-001",
    version: 12,
    date: "Sep 08, 2026",
    change: "Modified SSH authentication transport algorithms",
    impact: "Increased",
    controls: ["IA-2", "AC-17"],
    riskBefore: 55,
    riskAfter: 64,
    finding: "FND-00420",
  },
  {
    id: "drift-004",
    deviceId: "dev-001",
    version: 11,
    date: "Aug 30, 2026",
    change: "Hardened management-plane services and access-lists",
    impact: "Decreased",
    controls: ["CIS-5.1", "CIS-4.2"],
    riskBefore: 62,
    riskAfter: 55,
    finding: undefined,
  },
  {
    id: "drift-005",
    deviceId: "dev-002",
    version: 8,
    date: "Sep 21, 2026",
    change: "Removed legacy management service on external gateway",
    impact: "Decreased",
    controls: ["CIS-5.1", "AC-17"],
    riskBefore: 49,
    riskAfter: 42,
    finding: "FND-00421",
  },
  {
    id: "drift-006",
    deviceId: "dev-003",
    version: 5,
    date: "Sep 19, 2026",
    change: "Configured local logging buffer threshold below benchmark",
    impact: "Increased",
    controls: ["CIS-3.1", "AU-4"],
    riskBefore: 45,
    riskAfter: 51,
    finding: undefined,
  },
];

export const aiMappings: AiMapping[] = [
  {
    id: "MAP-001",
    syntax: "transport input ssh",
    vendor: "Cisco IOS-XE",
    confidence: 96,
    canonicalField: "remoteAccess.transport",
    suggestedValue: "SSH",
    reason:
      "Vendor syntax strongly maps to encrypted remote management transport.",
    status: "Needs review",
    reviewer: "Unassigned",
    date: "Sep 23, 2026",
  },
  {
    id: "MAP-002",
    syntax: "set service ssh",
    vendor: "Juniper Junos",
    confidence: 91,
    canonicalField: "remoteAccess.transport",
    suggestedValue: "SSH",
    reason: "Configuration enables SSH as the remote administration protocol.",
    status: "Needs review",
    reviewer: "Unassigned",
    date: "Sep 22, 2026",
  },
  {
    id: "MAP-003",
    syntax: "config system admin",
    vendor: "Fortinet FortiOS",
    confidence: 88,
    canonicalField: "authentication.admin",
    suggestedValue: "Local / centralized authentication",
    reason:
      "The syntax identifies the administrative authentication configuration block.",
    status: "Approved",
    reviewer: "Aarav Mehta",
    date: "Sep 20, 2026",
  },
  {
    id: "MAP-004",
    syntax: "service password-encryption",
    vendor: "Cisco IOS-XE",
    confidence: 94,
    canonicalField: "authentication.passwordProtection",
    suggestedValue: "Enabled",
    reason:
      "The command enables password protection for applicable configuration values.",
    status: "Rejected",
    reviewer: "Aarav Mehta",
    date: "Sep 19, 2026",
  },
];

export const reports: Report[] = [
  {
    id: "RPT-001",
    title: "Network Security Assessment",
    type: "Executive Summary",
    deviceId: "dev-001",
    auditId: "AUD-001",
    date: "Sep 23, 2026",
    status: "Ready",
    compliance: 74,
  },
  {
    id: "RPT-002",
    title: "Management Plane Findings",
    type: "Findings",
    deviceId: "dev-002",
    auditId: "AUD-002",
    date: "Sep 22, 2026",
    status: "Ready",
    compliance: 88,
  },
  {
    id: "RPT-003",
    title: "Framework Coverage Assessment",
    type: "Framework Mapping",
    deviceId: "dev-003",
    auditId: "AUD-003",
    date: "Sep 20, 2026",
    status: "Ready",
    compliance: 81,
  },
  {
    id: "RPT-004",
    title: "Risk Assessment",
    type: "Risk Assessment",
    deviceId: "dev-004",
    auditId: "AUD-004",
    date: "Sep 18, 2026",
    status: "Processing",
    compliance: 91,
  },
];

export const audits: Audit[] = [
  {
    id: "AUD-001",
    deviceId: "dev-001",
    configurationId: "CFG-001",
    date: "Sep 23, 2026",
    createdAt: "Sep 23, 2026 09:43",
    duration: "01m 42s",
    findings: 5,
    frameworks: ["CIS Controls v8", "NIST SP 800-53"],
    compliance: 74,
    status: "COMPLETED",
  },
  {
    id: "AUD-002",
    deviceId: "dev-002",
    configurationId: "CFG-003",
    date: "Sep 22, 2026",
    createdAt: "Sep 22, 2026 11:25",
    duration: "00m 58s",
    findings: 2,
    frameworks: ["CIS Controls v8"],
    compliance: 88,
    status: "COMPLETED",
  },
  {
    id: "AUD-003",
    deviceId: "dev-003",
    configurationId: "CFG-004",
    date: "Sep 20, 2026",
    createdAt: "Sep 20, 2026 16:35",
    duration: "01m 15s",
    findings: 3,
    frameworks: ["CIS Controls v8", "NIST SP 800-53"],
    compliance: 81,
    status: "COMPLETED",
  },
  {
    id: "AUD-004",
    deviceId: "dev-004",
    configurationId: "CFG-005",
    date: "Sep 18, 2026",
    createdAt: "Sep 18, 2026 08:05",
    duration: "00m 45s",
    findings: 1,
    frameworks: ["ISO/IEC 27001"],
    compliance: 91,
    status: "COMPLETED",
  },
];

export const findings: Finding[] = [
  {
    id: "F-001",
    deviceId: "dev-001",
    auditId: "AUD-001",
    control: "CIS-5.1",
    title: "Unencrypted management transport detected",
    severity: "Critical",
    status: "OPEN",
    line: 12,
    framework: "CIS Controls v8",
    createdAt: "Sep 23, 2026",
    rule: "CIS-5.1-VTY-SSH-ONLY",
    description:
      "VTY lines permit Telnet transport which transmits administrative credentials and sessions in cleartext over the network.",
    expected: "transport input ssh",
    actual: "transport input telnet ssh",
    impact:
      "Credentials subject to eavesdropping and replay attacks on management segments.",
    canonicalField: "remoteAccess.transport",
    remediation: [
      "Configure line vty 0 4 with 'transport input ssh'.",
      "Generate RSA crypto keys with modulus >= 2048 if not present.",
      "Verify SSH connectivity before disconnecting current session.",
    ],
  },
  {
    id: "F-002",
    deviceId: "dev-001",
    auditId: "AUD-001",
    control: "AC-17",
    title: "Remote access policy requires hardening",
    severity: "High",
    status: "IN_REVIEW",
    line: 15,
    framework: "NIST SP 800-53",
    createdAt: "Sep 23, 2026",
    rule: "NIST-AC17-TIMEOUT",
    description:
      "Administrative idle timeout is not configured or exceeds maximum allowed threshold of 10 minutes.",
    expected: "exec-timeout 10 0 (or lower)",
    actual: "exec-timeout unconfigured or default 0 0",
    impact:
      "Abandoned terminal sessions remain open indefinitely to unauthorized physical or adjacent network access.",
    canonicalField: "remoteAccess.sessionTimeout",
    remediation: [
      "Apply 'exec-timeout 10 0' to all line configurations.",
      "Apply TCP keepalive to dead peer sessions.",
    ],
  },
  {
    id: "F-003",
    deviceId: "dev-001",
    auditId: "AUD-001",
    control: "IA-2",
    title: "Administrative authentication configuration changed",
    severity: "Medium",
    status: "ACKNOWLEDGED",
    line: 9,
    framework: "NIST SP 800-53",
    createdAt: "Sep 23, 2026",
    rule: "NIST-IA2-MFA-CENTRAL",
    description:
      "Device relies solely on local database authentication instead of centralized TACACS+/RADIUS with MFA.",
    expected: "aaa authentication login default group tacacs+ local",
    actual: "aaa authentication login default local",
    impact:
      "Lack of centralized accounting, revoke ability, and multi-factor authentication audit trail.",
    canonicalField: "authentication.aaaScheme",
    remediation: [
      "Define centralized AAA server group.",
      "Enforce fallback to local only during network outage.",
    ],
  },
  {
    id: "F-004",
    deviceId: "dev-002",
    auditId: "AUD-002",
    control: "CIS-4.2",
    title: "Legacy management service configuration",
    severity: "Low",
    status: "RESOLVED",
    line: 5,
    framework: "CIS Controls v8",
    createdAt: "Sep 22, 2026",
    rule: "CIS-4.2-DISABLE-TELNET",
    description:
      "Legacy Telnet daemon was active in previous revision but has now been explicitly disabled.",
    expected: "set admin-telnet disable",
    actual: "set admin-telnet disable",
    impact: "Resolved: Unencrypted protocol attack vector mitigated.",
    canonicalField: "services.telnetDaemon",
    remediation: [
      "Verify admin-telnet remains disabled across future policy pushes.",
    ],
  },
  {
    id: "F-005",
    deviceId: "dev-003",
    auditId: "AUD-003",
    control: "CIS-6.1",
    title: "Time synchronization evidence is incomplete",
    severity: "Medium",
    status: "OPEN",
    line: 4,
    framework: "CIS Controls v8",
    createdAt: "Sep 20, 2026",
    rule: "CIS-6.1-NTP-SERVERS",
    description:
      "No authenticated NTP server source declared in running configuration evidence.",
    expected: "ntp server <ip> key <id>",
    actual: "No ntp server commands found",
    impact:
      "Forensic log timestamps cannot be guaranteed accurate for incident correlation.",
    canonicalField: "time.ntp.servers",
    remediation: [
      "Configure at least two authoritative Stratum-2 NTP servers.",
      "Enable NTP symmetric authentication keys.",
    ],
  },
];

export const frameworks: Framework[] = [
  {
    id: "cis-v8",
    name: "CIS Controls",
    version: "v8.0",
    category: "Security baseline",
    mappedRules: 42,
    coverage: 84,
    controls: 18,
    note: "Center for Internet Security Controls v8",
  },
  {
    id: "nist-800-53",
    name: "NIST SP 800-53",
    version: "Rev. 5",
    category: "Security & privacy",
    mappedRules: 36,
    coverage: 76,
    controls: 24,
    note: "Security and Privacy Controls for Information Systems",
  },
  {
    id: "stig",
    name: "DISA STIG",
    version: "2026",
    category: "Configuration hardening",
    mappedRules: 28,
    coverage: 71,
    controls: 16,
    note: "Security Technical Implementation Guide",
  },
  {
    id: "iso-27001",
    name: "ISO/IEC 27001",
    version: "2022",
    category: "Information security",
    mappedRules: 31,
    coverage: 79,
    controls: 21,
    note: "Information security management controls",
  },
];

export const dashboard: DashboardData = {
  riskTrend: [
    { month: "Apr", score: 57 },
    { month: "May", score: 54 },
    { month: "Jun", score: 52 },
    { month: "Jul", score: 49 },
    { month: "Aug", score: 48 },
    { month: "Sep", score: 46 },
  ],
  complianceTrend: [
    { month: "Apr", score: 71 },
    { month: "May", score: 73 },
    { month: "Jun", score: 75 },
    { month: "Jul", score: 77 },
    { month: "Aug", score: 78 },
    { month: "Sep", score: 81 },
  ],
  frameworkScores: [
    { label: "CIS v8", score: 84, name: "CIS Controls v8.0" },
    { label: "NIST 800-53", score: 76, name: "NIST SP 800-53 Rev. 5" },
    { label: "STIG", score: 71, name: "DISA STIG" },
    { label: "ISO 27001", score: 79, name: "ISO/IEC 27001:2022" },
  ],
};
