server:
  port: 8080

spring:
  application:
    name: nexus-comply-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/nexus_comply}
      auto-index-creation: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.nexuscomply: DEBUG
